/*
Ce fichier est à utiliser pour remplir les tables crées avec 'arch.sql'.
*/

INSERT INTO Sport (
  ('Individuel','Natation'),
  ('Individuel','Equitation'),
  ('Individuel','Athlétisme'),
  ('Collectif','Athlétisme'),
  ('Individuel','Gymnastique'),
  ('Collectif','Aviron'),
  ('Collectif','Badminton'),
  ('Collectif','Baseball'),
  ('Collectif','Basketball'),
  ('Individuel','Judo'),
  ('Individuel','Escrime'),
  ('Collectif','Escrime'),
  ('Collectif','Tennis'),
  ('Individuel','Tennis'),
  ('Collectif','Escrime'),
  ('Collectif','Tennis de table'),
  ('Individuel','Tennis de table'),
  ('Individuel','tir à l\'arc'),
  ('Individuel','volley ball')
);

INSERT INTO Athlete (

   ( 'Serena Armstrong','Espagne',2, 'femme' ,32),
   ( 'Azul Salamat','Autriche',13, 'femme' ,20),
   ( 'Lena Hamila','Australie',18, 'femme' ,18),
   ( 'Caroline Staut','Algérie',13, 'femme' ,19),
   ( 'Korra Cobain','Mexique',10, 'femme' ,21),
   ( 'Serena Armstrong','Espagne',1, 'femme' ,20),
   ( 'Chihiro Staley','Afrique du Sud',14, 'femme' ,22),
   ( 'Michaela Thompson','Albanie',14, 'femme' ,27),
   ( 'Penelope Fujisawa','États-Unis',10, 'femme' ,34),
   ( 'Sabrine Mercury','Russie',12, 'femme' ,23),
   ( 'Annalise Moore','Irak',10, 'femme' ,24),
   ( 'Karima Mendoza','Sénégal',16, 'femme' ,27),
   ( 'Akira Iwana','Etats-Unis',18, 'femme' ,35),
   ( 'Annalise Moore','Irak',17, 'femme' ,25),
   ( 'Jeanne Onizuka','France',14, 'femme' ,26),
   ( 'Angelina Cruz','Iran',10, 'femme' ,24),
   ( 'Karima Mendoza','Sénégal',19, 'femme' ,22),
   ( 'Angelina Cruz','Iran',1, 'femme' ,31),
   ( 'Annalise Moore','Irak',14, 'femme' ,25),
   ( 'Leta Leprevault','Angleterre',10, 'femme' ,32),
   ( 'Annalise Moore','Irak',7, 'femme' ,34),
   ( 'Sabrine Mercury','Russie',8, 'femme' ,29),
   ( 'Emilie Hendrix','Chine',3, 'femme' ,35),
   ( 'Coraline Felipe','Maroc',15, 'femme' ,34),
   ( 'Sabrine Mercury','Russie',7, 'femme' ,31),
   ( 'Caroline Staut','Algérie',1, 'femme' ,27),
   ( 'Angelina Cruz','Iran',17, 'femme' ,17),
   ( 'Coraline Felipe','Maroc',3, 'femme' ,17),
   ( 'Morena Oda','Italie',11, 'femme' ,22),
   ( 'Serena Armstrong','Espagne',5, 'femme' ,26),
   ( 'Annalise Moore','Irak',10, 'femme' ,32),
   ( 'Azul Salamat','Autriche',17, 'femme' ,35),
   ( 'Serena Armstrong','Espagne',13, 'femme' ,34),
   ( 'Korra Cobain','Mexique',6, 'femme' ,22),
   ( 'Caroline Staut','Algérie',5, 'femme' ,29),
   ( 'Korra Cobain','Mexique',6, 'femme' ,26),
   ( 'Annalise Moore','Irak',13, 'femme' ,22),
   ( 'Chihiro Staley','Afrique du Sud',2, 'femme' ,31),
   ( 'Lena Hamila','Australie',3, 'femme' ,23),
   ( 'Morena Oda','Italie',5, 'femme' ,24),
   ( 'Michaela Thompson','Albanie',10, 'femme' ,20),
   ( 'Emilie Hendrix','Chine',2, 'femme' ,25),
   ( 'Korra Cobain','Mexique',5, 'femme' ,27),
   ( 'Morena Oda','Italie',14, 'femme' ,27),
   ( 'Jeanne Onizuka','France',2, 'femme' ,31),
   ( 'Marie Enripsia','Allemagne',5, 'femme' ,26),
   ( 'Penelope Fujisawa','États-Unis',8, 'femme' ,26),
   ( 'Jeanne Onizuka','France',5, 'femme' ,29),
   ( 'Korra Cobain','Mexique',11, 'femme' ,27),
   ( 'Korra Cobain','Mexique',2, 'femme' ,22),
   ( 'Korra Cobain','Mexique',19, 'femme' ,34),
   ( 'Angelina Cruz','Iran',12, 'femme' ,27),
   ( 'Leta Leprevault','Angleterre',14, 'femme' ,35),
   ( 'Angelina Cruz','Iran',15, 'femme' ,20),
   ( 'Frank Brachma','Russie',13, 'homme' ,21),
   ( 'Eikichi Ramazi','Allemagne',1, 'homme' ,30),
   ( 'Kevin Avery','Chine',12, 'homme' ,30),
   ( 'Madiba Havard','Australie',1, 'homme' ,19),
   ( 'Montgomery Dagda','Angleterre',4, 'homme' ,33),
   ( 'Moussa Perez','Mexique',5, 'homme' ,20),
   ( 'Toru Werner','Espagne',8, 'homme' ,18),
   ( 'Eikichi Ramazi','Allemagne',7, 'homme' ,35),
   ( 'Frank Brachma','Russie',6, 'homme' ,18),
   ( 'Montgomery Dagda','Angleterre',4, 'homme' ,34),
   ( 'Madiba Havard','Australie',2, 'homme' ,34),
   ( 'Adrian Izebel','Iran',15, 'homme' ,20),
   ( 'Zuko Sunil','Etats-Unis',18, 'homme' ,23),
   ( 'Adrian Izebel','Iran',2, 'homme' ,33),
   ( 'Karim Meklat','Sénégal',3, 'homme' ,26),
   ( 'Richard Edita','États-Unis',3, 'homme' ,22),
   ( 'Manuel Keala','Albanie',2, 'homme' ,24),
   ( 'Michel Neha','Italie',2, 'homme' ,33),
   ( 'Montgomery Dagda','Angleterre',18, 'homme' ,23),
   ( 'Richard Edita','États-Unis',2, 'homme' ,25),
   ( 'Aang Eber','Maroc',16, 'homme' ,19),
   ( 'Eikichi Ramazi','Allemagne',2, 'homme' ,34),
   ( 'Jean Haraldur','France',15, 'homme' ,26),
   ( 'Abdelkarim Perec','Afrique du Sud',7, 'homme' ,27),
   ( 'Adrian Izebel','Iran',9, 'homme' ,17),
   ( 'Karim Meklat','Sénégal',13, 'homme' ,18),
   ( 'Moussa Perez','Mexique',4, 'homme' ,35),
   ( 'Abdelkarim Perec','Afrique du Sud',8, 'homme' ,35),
   ( 'Luke Shyamala','Autriche',9, 'homme' ,22),
   ( 'Madiba Havard','Australie',17, 'homme' ,33),
   ( 'Abdelkarim Perec','Afrique du Sud',2, 'homme' ,22),
   ( 'Benjamin Gulnaz','Irak',7, 'homme' ,29),
   ( 'Kevin Avery','Chine',7, 'homme' ,30),
   ( 'Karim Meklat','Sénégal',14, 'homme' ,30),
   ( 'Aang Eber','Maroc',17, 'homme' ,26),
   ( 'Adrian Izebel','Iran',16, 'homme' ,28),
   ( 'Zuko Sunil','Etats-Unis',18, 'homme' ,34),
   ( 'Jean Haraldur','France',18, 'homme' ,17),
   ( 'Kevin Avery','Chine',6, 'homme' ,18),
   ( 'Adrian Izebel','Iran',7, 'homme' ,31),
   ( 'Luke Shyamala','Autriche',7, 'homme' ,21),
   ( 'Aang Eber','Maroc',1, 'homme' ,35),
   ( 'Karim Meklat','Sénégal',17, 'homme' ,18),
   ( 'Eikichi Ramazi','Allemagne',2, 'homme' ,30),
   ( 'Karim Meklat','Sénégal',6, 'homme' ,19),
   ( 'Madiba Havard','Australie',11, 'homme' ,17),
   ( 'Toru Werner','Espagne',17, 'homme' ,24),
   ( 'Luke Shyamala','Autriche',9, 'homme' ,34),
   ( 'Zuko Sunil','Etats-Unis',19, 'homme' ,23),
   ( 'Michel Neha','Italie',19, 'homme' ,28),
   ( 'Abdelkarim Perec','Afrique du Sud',5, 'homme' ,26),
   ( 'Abdelkarim Perec','Afrique du Sud',13, 'homme' ,31),
   ( 'Moussa Perez','Mexique',10, 'homme' ,27),
   ( 'Frank Brachma','Russie',1, 'homme' ,34)


);

INSERT INTO Equipe (

  ('Etats-Unis',15,'femme'),
  ('Etats-Unis',15,'homme'),
  ('Afrique du Sud',13,'femme'),
  ('Afrique du Sud',13,'homme'),
  ('Allemagne',15,'femme'),
  ('Allemagne',15,'homme'),
  ('Iran',10,'femme'),
  ('Iran',10,'homme'),
  ('Albanie',1,'femme'),
  ('Albanie',1,'homme'),
  ('Italie',14,'femme'),
  ('Italie',14,'homme'),
  ('Espagne',6,'femme'),
  ('Espagne',6,'homme'),
  ('Russie',3,'femme'),
  ('Russie',3,'homme'),
  ('Angleterre',7,'femme'),
  ('Angleterre',7,'homme'),
  ('Espagne',10,'femme'),
  ('Espagne',10,'homme'),
  ('Irak',15,'femme'),
  ('Irak',15,'homme'),
  ('Autriche',4,'femme'),
  ('Autriche',4,'homme'),
  ('Autriche',4,'femme'),
  ('Autriche',4,'homme'),
  ('Albanie',14,'femme'),
  ('Albanie',14,'homme'),
  ('Maroc',18,'femme'),
  ('Maroc',18,'homme'),
  ('Etats-Unis',3,'femme'),
  ('Etats-Unis',3,'homme'),
  ('Albanie',10,'femme'),
  ('Albanie',10,'homme'),
  ('Maroc',14,'femme'),
  ('Maroc',14,'homme'),
  ('Mexique',16,'femme'),
  ('Mexique',16,'homme'),
  ('États-Unis',16,'femme'),
  ('États-Unis',16,'homme'),
  ('Afrique du Sud',2,'femme'),
  ('Afrique du Sud',2,'homme'),
  ('Angleterre',3,'femme'),
  ('Angleterre',3,'homme'),
  ('Afrique du Sud',6,'femme'),
  ('Afrique du Sud',6,'homme'),
  ('Chine',3,'femme'),
  ('Chine',3,'homme'),
  ('Maroc',12,'femme'),
  ('Maroc',12,'homme')

);

INSERT INTO EpreuveIndividuel (

);
