
-- Ce fichier est à utiliser pour remplir les tables crées avec 'arch.sql'.


INSERT INTO Sport (type, nomSport) VALUES
  ('Individuel','Natation'),
  ('Individuel','Equitation'),
  ('Individuel','Athlétisme'),
  ('Collectif','Athlétisme'),
  ('Individuel','Gymnastique'),
  ('Collectif','Aviron'),
  ('Collectif','Badminton'),
  ('Collectif','Baseball'),
  ('Collectif','Basketball'),
  ('Individuel','Judo'),
  ('Individuel','Escrime'),
  ('Collectif','Escrime'),
  ('Collectif','Tennis'),
  ('Individuel','Tennis'),
  ('Collectif','Escrime'),
  ('Collectif','Tennis de Table'),
  ('Individuel','Tennis de Table'),
  ('Individuel','Tir à l Arc'),
  ('Individuel','Volley Ball');

INSERT INTO Athlete (NomAthlete, Pays, IDSport, sexe, age) VALUES
  ('Carlito Neves', 'Portugal', 5, 'Homme', 25),
  ('Zhen Shun', 'Chine', 12, 'Homme', 22),
  ('Tolstaya Valerievna', 'Russie', 5, 'Femme', 19),
  ('Tsuo Yixing', 'Chine', 11, 'Femme', 35),
  ('Berend Pultz', 'Allemagne', 4, 'Homme', 33),
  ('David Brown', 'Etats Unis', 5, 'Homme', 33),
  ('Ramla Badie', 'Algerie', 1, 'Femme', 18),
  ('Paula Anjos', 'Brésil', 10, 'Femme', 22),
  ('Grace Dixon', 'Etats Unis', 4, 'Femme', 22),
  ('Jean-François Dupont', 'France', 8, 'Homme', 19),
  ('Nardin Timurovich', 'Russie', 9, 'Homme', 26),
  ('Fabiano Ávila', 'Portugal', 3, 'Homme', 19),
  ('Shao Zan', 'Chine', 10, 'Femme', 25),
  ('Shi Lingxin', 'Chine', 7, 'Homme', 17),
  ('Marie Sharpe', 'Etats Unis', 9, 'Femme', 23),
  ('Elliot Robinson', 'Etats Unis', 8, 'Homme', 28),
  ('Ana Velázquez', 'Espagne', 3, 'Femme', 23),
  ('Tolstaya Valerievna', 'Russie', 7, 'Femme', 31),
  ('Pong Woo-Jin', 'Corée Du Sud', 3, 'Homme', 26),
  ('Arina Vitalievna', 'Russie', 5, 'Femme', 35),
  ('Violeta Tamayo', 'Espagne', 1, 'Femme', 29),
  ('Shao Feng', 'Chine', 13, 'Femme', 31),
  ('Ri Hae-Seong', 'Corée Du Sud', 4, 'Homme', 32),
  ('Luzia Henriques', 'Portugal', 1, 'Femme', 25),
  ('Eto Masaharu', 'Japon', 6, 'Homme', 33),
  ('Melissa Booth', 'Etats Unis', 3, 'Femme', 18),
  ('Harako Ito', 'Japon', 4, 'Femme', 23),
  ('Lena Cavoli', 'Italie', 5, 'Femme', 32),
  ('Azeema al-Farra', 'Algerie', 3, 'Homme', 29),
  ('Lena Sequeira', 'Portugal', 3, 'Femme', 20),
  ('Katerine Bauer', 'Allemagne', 5, 'Femme', 27),
  ('Kyong Tohyon', 'Corée Du Sud', 4, 'Homme', 23),
  ('Hawraa al-Zaidi', 'Algerie', 4, 'Femme', 23),
  ('Takemoto Katsunosuki', 'Japon', 5, 'Homme', 28),
  ('Tharwa el-Beydoun', 'Algerie', 3, 'Femme', 20),
  ('Usain Balt', 'Jamaique', 6, 'Homme', 20),
  ('Zufar al-Jabara', 'Algerie', 6, 'Homme', 29),
  ('Eli Osborn', 'Canada', 12, 'Homme', 27),
  ('Louis Morel', 'France', 3, 'Homme', 24),
  ('Wu Cai', 'Chine', 4, 'Femme', 22),
  ('Yoshiyuki Eiko', 'Japon', 9, 'Femme', 27),
  ('Kum Ki-Nam', 'Corée Du Sud', 10, 'Homme', 33),
  ('Scott Davies', 'Etats Unis', 2, 'Homme', 17),
  ('Arefyev Dmitrievich', 'Russie', 1, 'Homme', 35),
  ('Eristov Makarovich', 'Russie', 3, 'Homme', 23),
  ('Wang Hui', 'Chine', 3, 'Homme', 35),
  ('Harley Parry', 'Canada', 13, 'Homme', 32),
  ('Petrichia Paccollu', 'Italie', 3, 'Femme', 24),
  ('Naiara Cruz', 'Portugal', 8, 'Femme', 28),
  ('Tsu Xi', 'Chine', 5, 'Femme', 34),
  ('Chi Shi-Won', 'Corée Du Sud', 8, 'Femme', 20),
  ('Celso Matos', 'Portugal', 1, 'Homme', 27),
  ('Swen Hildebrandt', 'Allemagne', 9, 'Homme', 31),
  ('Alexandre Peletier', 'France', 5, 'Homme', 33),
  ('Dylan Elliott', 'Etats Unis', 8, 'Homme', 20),
  ('Zoe Chapman', 'Royaume Uni', 1, 'Femme', 17),
  ('Keyla Atkins', 'Royaume Uni', 7, 'Femme', 32),
  ('Archer Wood', 'Canada', 3, 'Homme', 24),
  ('Lillie Slater', 'Royaume Uni', 7, 'Femme', 33),
  ('Hilda Bohlen', 'Allemagne', 11, 'Femme', 19),
  ('Xuan Nuan', 'Chine', 5, 'Femme', 32),
  ('Trayvon Vernon', 'Jamaique', 10, 'Homme', 32),
  ('Harvey Carney', 'Etats Unis', 10, 'Homme', 28),
  ('Matilda Walker', 'Canada', 10, 'Femme', 19),
  ('Hyon Chunho', 'Corée Du Sud', 12, 'Femme', 18),
  ('Isaac Williams', 'Etats Unis', 7, 'Homme', 28),
  ('Ewan Hussain', 'Etats Unis', 11, 'Homme', 30),
  ('Françoise Levet', 'France', 13, 'Femme', 20),
  ('Théodore Hauet', 'France', 4, 'Homme', 28),
  ('Joana Queiros', 'Portugal', 12, 'Femme', 34),
  ('Jesús Campos', 'Espagne', 3, 'Homme', 35),
  ('Jack Webb', 'Royaume Uni', 2, 'Homme', 30),
  ('Valfrido Ciminelli', 'Italie', 11, 'Homme', 25),
  ('Ding Chun', 'Chine', 8, 'Femme', 32),
  ('Camila Elvira', 'Espagne', 3, 'Femme', 30),
  ('Friedrich Klengel', 'Allemagne', 9, 'Homme', 26),
  ('Lillie Slater', 'Royaume Uni', 4, 'Homme', 29),
  ('Quinzio Casagranda', 'Italie', 3, 'Homme', 20),
  ('Huo Zhelan', 'Chine', 13, 'Femme', 32),
  ('Gautier Cartier', 'France', 3, 'Homme', 30),
  ('Leeroy Jenkins', 'Royaume Uni', 7, 'Homme', 24),
  ('Oscar Mills', 'Etats Unis', 3, 'Homme', 25),
  ('Riley Dean', 'Royaume Uni', 1, 'Homme', 27),
  ('Grete Reichenbach', 'Allemagne', 3, 'Femme', 26),
  ('Tarasov Andreevich', 'Russie', 6, 'Homme', 24),
  ('Silvio Cafarella', 'Italie', 3, 'Homme', 29),
  ('Mo Seong', 'Corée Du Sud', 8, 'Femme', 33),
  ('Ruy Rego', 'Brésil', 13, 'Homme', 31),
  ('Pedro Lopes', 'Portugal', 7, 'Homme', 19),
  ('Tyjon Stackpole', 'Jamaique', 5, 'Homme', 34),
  ('Kendra Prince', 'Canada', 4, 'Femme', 21),
  ('Luana Sancho', 'Espagne', 4, 'Femme', 31),
  ('Johanna Pöpel', 'Allemagne', 2, 'Femme', 33),
  ('Phoebe Cooke', 'Royaume Uni', 13, 'Femme', 29),
  ('Mao Cai', 'Chine', 4, 'Femme', 21),
  ('Samuel Bötticher', 'Allemagne', 4, 'Homme', 35),
  ('Yokoyama Kiemon', 'Japon', 11, 'Homme', 25),
  ('Ercolano Tartaglione', 'Italie', 1, 'Homme', 35),
  ('Miriam Olberding', 'Allemagne', 13, 'Femme', 24),
  ('Melissa Saavedra', 'Espagne', 2, 'Femme', 27),
  ('Hans Zimmer', 'Allemagne', 3, 'Homme', 23),
  ('Maisie Clark', 'Etats Unis', 5, 'Femme', 29),
  ('Corey Lane', 'Royaume Uni', 6, 'Homme', 27),
  ('Ewan Porter', 'Etats Unis', 13, 'Homme', 29),
  ('Zita Di Donato', 'Italie', 6, 'Femme', 21),
  ('Chun Kun-Woo', 'Corée Du Sud', 13, 'Homme', 29),
  ('Chekib Hamila', 'Algerie', 2, 'Homme', 21),
  ('Ulisse Pellecchia', 'Italie', 13, 'Homme', 26),
  ('Kilian Fassbender', 'Allemagne', 8, 'Homme', 17),
  ('Duda Bento', 'Portugal', 2, 'Homme', 23),
  ('Krutina Nikitovna', 'Russie', 2, 'Femme', 33),
  ('Simone Neufeld', 'Allemagne', 1, 'Femme', 27),
  ('Maida Del Grosso', 'Italie', 9, 'Femme', 30),
  ('Brisa Andrade', 'Espagne', 5, 'Femme', 25),
  ('Elías Cambeiro', 'Espagne', 2, 'Homme', 33),
  ('Chikae Megumi', 'Japon', 9, 'Femme', 17),
  ('Maia Morais', 'Portugal', 8, 'Femme', 27),
  ('Legend Chen', 'Canada', 10, 'Homme', 19),
  ('Mok Tae-Woo', 'Corée Du Sud', 7, 'Homme', 33),
  ('Josh Miller', 'Canada', 6, 'Homme', 25),
  ('Christelle Maitre', 'France', 5, 'Femme', 22),
  ('Benjamin Courbis', 'France', 6, 'Homme', 20),
  ('Aaden Jimenez', 'Royaume Uni', 5, 'Homme', 34),
  ('Annick Bessette', 'France', 8, 'Femme', 35),
  ('Xuan Yang', 'Chine', 3, 'Homme', 26),
  ('Shao Huo', 'Chine', 2, 'Femme', 32),
  ('Eros Sessa', 'Italie', 7, 'Homme', 27),
  ('Jenson Rees', 'Etats Unis', 3, 'Homme', 24),
  ('Sara Cortes', 'Portugal', 3, 'Femme', 34),
  ('Tsu Pao', 'Corée Du Sud', 12, 'Homme', 35),
  ('Joelle Gordan', 'Jamaique', 11, 'Femme', 33),
  ('Rami Salek', 'Algerie', 8, 'Homme', 22),
  ('Luciana del Pozo', 'Espagne', 3, 'Femme', 18),
  ('Sigfrido Bottone', 'Italie', 9, 'Homme', 31),
  ('Ludwig Haussegger', 'Allemagne', 13, 'Homme', 26),
  ('Ollie Hamilton', 'Canada', 2, 'Homme', 28),
  ('Alyssa Herring', 'Royaume Uni', 9, 'Femme', 21),
  ('Pabla Escobaras', 'Espagne', 7, 'Femme', 22),
  ('Abram Conner', 'Etats Unis', 3, 'Homme', 35),
  ('Mônica Luz', 'Portugal', 11, 'Femme', 28),
  ('Benedita Mendez', 'Portugal', 2, 'Femme', 27),
  ('Timoshenko Yakovich', 'Russie', 4, 'Homme', 33),
  ('Zac Doyle', 'Etats Unis', 4, 'Homme', 34),
  ('Kale Mcclure', 'Canada', 5, 'Homme', 21),
  ('Cyka Annikov', 'Russie', 5, 'Femme', 35),
  ('Joe Moore', 'Etats Unis', 3, 'Homme', 31),
  ('Marie Pluchart', 'France', 8, 'Femme', 22),
  ('Shmelev Stanislavovich', 'Russie', 5, 'Homme', 27),
  ('Shao Feng', 'Chine', 1, 'Femme', 21),
  ('Paolo Castronovo', 'Italie', 7, 'Homme', 26),
  ('Liu Shun', 'Chine', 13, 'Homme', 24),
  ('Jeremy Delaney', 'Etats Unis', 2, 'Homme', 29),
  ('Greta Giardino', 'Italie', 6, 'Femme', 20),
  ('Julia Simmons', 'Etats Unis', 11, 'Femme', 23),
  ('Euduard', 'Italie', 1, 'Homme', 24),
  ('Lilyana West', 'Royaume Uni', 1, 'Femme', 20),
  ('Sunada Tadashi', 'Japon', 1, 'Homme', 35),
  ('Chang Chun', 'Chine', 1, 'Homme', 22),
  ('Andreas Wernz', 'Allemagne', 5, 'Homme', 17),
  ('Dominga Alvas', 'Portugal', 9, 'Femme', 27),
  ('Luis López', 'Espagne', 4, 'Homme', 20),
  ('Loris Calcagni', 'Italie', 3, 'Homme', 31),
  ('Jean-Charles Jacquet', 'France', 9, 'Homme', 24),
  ('Kryukova Semyonovna', 'Russie', 9, 'Femme', 20),
  ('Cheng Da', 'Chine', 4, 'Homme', 29),
  ('Oscar James', 'Royaume Uni', 7, 'Homme', 29),
  ('Lexi Barnes', 'Etats Unis', 2, 'Femme', 27),
  ('Cody Foster', 'Royaume Uni', 2, 'Homme', 18),
  ('Bella Reynolds', 'Etats Unis', 11, 'Femme', 28),
  ('Fujiwara Toyozo', 'Japon', 5, 'Homme', 27),
  ('Nashka Artemievna', 'Russie', 13, 'Femme', 32),
  ('Laila Rahaim', 'Algerie', 3, 'Femme', 21),
  ('Nina Mancebo', 'Espagne', 8, 'Femme', 17),
  ('Matthew Fox', 'Canada', 1, 'Homme', 23),
  ('Madilynn Mullins', 'Etats Unis', 10, 'Femme', 18),
  ('Elda Liberati', 'Italie', 9, 'Femme', 25),
  ('Felicita Da Silva', 'Brésil', 2, 'Femme', 22),
  ('Miguel Patao', 'Portugal', 2, 'Homme', 32),
  ('Scott White', 'Royaume Uni', 3, 'Homme', 34),
  ('Lúcia Dias', 'Brésil', 7, 'Femme', 33),
  ('Aleksei Dima', 'Russie', 3, 'Homme', 35),
  ('Giosuele Scacco', 'Italie', 3, 'Homme', 24),
  ('Spencer Rogers', 'Etats Unis', 4, 'Femme', 22),
  ('Tommy Lane', 'Etats Unis', 6, 'Homme', 17),
  ('Guillaume Bassot', 'France', 3, 'Homme', 31),
  ('Jordan Philippon', 'France', 10, 'Homme', 29),
  ('Caitlin Dawson', 'Royaume Uni', 11, 'Femme', 34),
  ('Ramon Morillo', 'Espagne', 13, 'Homme', 18),
  ('Eleonora Felicetti', 'Italie', 13, 'Femme', 23),
  ('Shiroma Sakamae', 'Japon', 1, 'Femme', 25),
  ('Nagao Yukichi', 'Japon', 3, 'Homme', 29),
  ('Travis Whitaker', 'Etats Unis', 11, 'Homme', 25),
  ('Husni al-Kalil', 'Algerie', 7, 'Homme', 31),
  ('Hong Yo-Han', 'Corée Du Sud', 12, 'Homme', 29),
  ('John Padding', 'Canada', 5, 'Homme', 25),
  ('Long Hu', 'Chine', 13, 'Homme', 35),
  ('Lívia Silvestra', 'Brésil', 8, 'Femme', 33),
  ('Snetkova Vitalievna', 'Espagne', 9, 'Femme', 23),
  ('Gilberto Seixas', 'Portugal', 8, 'Homme', 27),
  ('Adrian Barrios', 'Espagne', 5, 'Homme', 24),
  ('Emily Williams', 'Canada', 4, 'Femme', 20),
  ('Lai Shi', 'Chine', 12, 'Femme', 34);

INSERT INTO Equipe (Pays, IDSport, sexe) VALUES
  ('Etats-Unis',15,'femme'),
  ('Etats-Unis',15,'homme'),
  ('Afrique du Sud',13,'femme'),
  ('Afrique du Sud',13,'homme'),
  ('Allemagne',15,'femme'),
  ('Allemagne',15,'homme'),
  ('Iran',10,'femme'),
  ('Iran',10,'homme'),
  ('Albanie',1,'femme'),
  ('Albanie',1,'homme'),
  ('Italie',14,'femme'),
  ('Italie',14,'homme'),
  ('Espagne',6,'femme'),
  ('Espagne',6,'homme'),
  ('Russie',3,'femme'),
  ('Russie',3,'homme'),
  ('Angleterre',7,'femme'),
  ('Angleterre',7,'homme'),
  ('Espagne',10,'femme'),
  ('Espagne',10,'homme'),
  ('Irak',15,'femme'),
  ('Irak',15,'homme'),
  ('Autriche',4,'femme'),
  ('Autriche',4,'homme'),
  ('Albanie',4,'femme'),
  ('Albanie',14,'homme'),
  ('Maroc',18,'femme'),
  ('Maroc',18,'homme'),
  ('Etats-Unis',3,'femme'),
  ('Etats-Unis',3,'homme'),
  ('Albanie',10,'femme'),
  ('Albanie',10,'homme'),
  ('Maroc',14,'femme'),
  ('Maroc',14,'homme'),
  ('Mexique',16,'femme'),
  ('Mexique',16,'homme'),
  ('États-Unis',16,'femme'),
  ('États-Unis',16,'homme'),
  ('Afrique du Sud',2,'femme'),
  ('Afrique du Sud',2,'homme'),
  ('Angleterre',3,'femme'),
  ('Angleterre',3,'homme'),
  ('Afrique du Sud',6,'femme'),
  ('Afrique du Sud',6,'homme'),
  ('Chine',3,'femme'),
  ('Chine',3,'homme'),
  ('Maroc',12,'femme'),
  ('Maroc',12,'homme');

INSERT INTO EpreuveCollective (IDEpreuve,IDSport,nomEpreuve,IDEquipeGagnanteOr,IDEquipeGagnanteArgent,IDEquipeGagnanteBronze) VALUES
    (4,'100m',23)
